In [1]:
import minari
import torch
from torch.utils.data import DataLoader, TensorDataset
import numpy as np

In [ ]:

# Need to run 'minari download D4RL/pointmaze/large-dense-v2'
dataset = minari.load_dataset('D4RL/pointmaze/large-dense-v2')
env  = dataset.recover_environment()


In [ ]:
for episode in dataset:
    print(f"EPISODE ID {episode.id}")

In [ ]:

# Extract all episodes
obs_list, action_list = [], []
for episode in dataset:
    obs_list.append(episode.observations)   # States
    action_list.append(episode.actions)     # Actions

 

Number of episodes: 3360


In [14]:
   
print(f"Number of episodes: {len(action_list)}")
print(action_list[0])

Number of episodes: 3360
[[-1.          1.        ]
 [-1.          0.60534286]
 [-1.          1.        ]
 [-1.          0.66309685]
 [-1.          0.21018419]
 [-1.          0.46562007]
 [-1.         -0.00867026]
 [-1.          0.0050581 ]
 [-1.          1.        ]
 [-1.         -0.0286825 ]
 [-1.          0.41782415]
 [-1.          0.03856557]
 [-1.         -1.        ]
 [-1.         -1.        ]
 [-1.         -0.80939895]
 [-1.         -1.        ]
 [-1.         -0.38640326]
 [-0.38754123 -0.05523457]
 [-0.36147323  0.36602357]
 [-0.31305072  0.04503201]
 [ 0.20840502 -1.        ]
 [ 0.7697003   0.37685883]
 [ 1.         -0.02362734]
 [ 1.          0.17727645]
 [ 1.          1.        ]
 [ 0.8132373  -0.8952025 ]
 [ 1.         -0.5845947 ]
 [ 1.          0.47883394]
 [-1.         -0.8282448 ]
 [-1.         -0.7694071 ]
 [-1.         -1.        ]
 [-1.         -0.2850666 ]
 [-1.         -0.69116926]
 [-1.         -0.24789102]
 [-1.         -0.63646996]
 [-1.         -0.5353314 ]
 [-

In [ ]:
# Print the first observation
print("First observation:", obs_list[0])
print("Observation keys:", obs_list[0].keys() if isinstance(obs_list[0], dict) else "Not a dictionary")

# Print the first action
print("First action:", action_list[0])
print("Action keys:", action_list[0].keys() if isinstance(action_list[0], dict) else "Not a dictionary")

First observation: {'achieved_goal': array([[ 2.34218591, -1.16204705],
       [ 2.33980427, -1.15966541],
       [ 2.33504666, -1.15584774],
       [ 2.32791875, -1.14965752],
       [ 2.31842618, -1.14190278],
       [ 2.30657457, -1.13366593],
       [ 2.29236955, -1.12433977],
       [ 2.27581673, -1.11505646],
       [ 2.25692169, -1.10578321],
       [ 2.23569001, -1.09415041],
       [ 2.21212726, -1.08261363],
       [ 2.18623899, -1.07010922],
       [ 2.15803074, -1.05754274],
       [ 2.12750803, -1.04738783],
       [ 2.09467638, -1.03963874],
       [ 2.05954128, -1.0338358 ],
       [ 2.02210823, -1.03042832],
       [ 1.98238268, -1.02794923],
       [ 1.94182877, -1.02560759],
       [ 1.90051054, -1.0223998 ],
       [ 1.85854514, -1.01909239],
       [ 1.81717604, -1.0181745 ],
       [ 1.77773861, -1.01636125],
       [ 1.74077674, -1.0146086 ],
       [ 1.70628454, -1.01243791],
       [ 1.67425613, -1.00789075],
       [ 1.64424083, -1.00548647],
       [ 1.6166786

In [ ]:
#x, y and, observation
print(obs_list[0]['observation'])

[[ 2.34218591 -1.16204705  0.          0.        ]
 [ 2.33980427 -1.15966541 -0.23816384  0.23816384]
 [ 2.33504666 -1.15584774 -0.47576046  0.3817674 ]
 ...
 [-4.20278244  2.85508925 -5.08464462 -0.01004078]
 [-4.25224439  2.85672183 -4.94619477  0.16325756]
 [-4.2992069   2.85808562 -4.69625088  0.13637893]]


In [40]:
# Process observations (trajectory)
obs_list_fixed = []
for obs in obs_list:
    if isinstance(obs, dict):
        obs = obs['observation']  # Adjust key if necessary
    obs_list_fixed.append(np.array(obs, dtype=np.float32))

# Convert list of observations into a single NumPy array
obs_array = np.vstack(obs_list_fixed)

# Convert to tensor
obs_tensor = torch.tensor(obs_array, dtype=torch.float32)

# Create TensorDataset (only observations)
maze_dataset = TensorDataset(obs_tensor)

# Create DataLoader
dataloader = DataLoader(maze_dataset, batch_size=128, shuffle=True)

# Print a sample batch
for obs_batch in dataloader:
    print("Observation Batch Shape:", obs_batch[0].shape)  # Indexing because TensorDataset returns a tuple
    print(obs_batch[0])
    break

Observation Batch Shape: torch.Size([128, 4])
tensor([[-0.8218, -2.9855,  4.2560, -0.0606],
        [ 0.3178, -0.1015, -0.1984, -3.6297],
        [ 1.3397, -1.0942,  3.1666, -0.1639],
        [-2.6424,  2.8745,  3.4892, -0.0841],
        [ 0.4420,  1.9755,  0.7564, -2.8359],
        [-4.6021,  0.9344,  1.2394, -1.8068],
        [ 0.3001,  0.9973, -1.9519,  1.1302],
        [ 3.6965,  0.8514, -5.0761,  0.1589],
        [ 4.5045,  2.9106,  0.0816, -2.2854],
        [ 0.5177, -3.0203,  1.5660,  1.3083],
        [ 2.0484, -1.1430, -5.1541, -0.3994],
        [ 0.3480,  2.2055, -0.8860,  4.6836],
        [ 4.3374, -0.0815, -0.0382,  3.7093],
        [ 4.3732,  0.6404,  0.2549,  4.4286],
        [ 2.5279,  2.8685,  2.5351, -1.5117],
        [-1.7346,  3.0602, -2.5951,  0.0645],
        [ 4.4355,  0.7147, -0.0389,  3.8891],
        [-4.6145,  1.0249, -0.1176, -3.6316],
        [ 3.3424, -1.0267, -3.9880,  0.2846],
        [-4.5330,  0.8947, -0.5258, -2.9381],
        [ 1.5902, -1.0822,  4.5144